export const buttons = [
    {caractere:'AC', estilo: 'caracteres'},
    {caractere:'DEL', estilo: 'caracteres'},
    {caractere:'%', estilo: 'caracteres'},
    {caractere:'/', estilo: 'caracteres'},
    {caractere: 7, estilo: 'numbers'},
    {caractere: 8, estilo: 'numbers'},
    {caractere: 9, estilo: 'numbers'},
    {caractere:'*', estilo: 'caracteres'},
    {caractere: 4, estilo: 'numbers'},
    {caractere: 5, estilo: 'numbers'},
    {caractere: 6, estilo: 'numbers'},
    {caractere:'-', estilo: 'caracteres'},
    {caractere: 3, estilo: 'numbers'},
    {caractere: 2, estilo: 'numbers'},
    {caractere: 1, estilo: 'numbers'},
    {caractere:'+', estilo: 'caracteres'},
    {caractere:'.', estilo: 'caracteres'},
    {caractere: 0, estilo: 'numbers'}, 
    {caractere:'+/-', estilo: 'caracteres'},
    {caractere:'=', estilo: 'equalSign'},
    ];